spring:
  application:
     name: shoes-store
  datasource:
    url: jdbc:mysql://localhost:3306/shoesstore
    username: root
    password: 0123456789
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
       ddl-auto: update
    show-sql: true
